INSERT INTO `all clients` VALUES ('Acajou (Pty) Ltd', 'Mungofa B.', 'SNH_l_011', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Accredited Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_025', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Advanced Terminations and Joints (Pty) Ltd', 'Helga Lotter', 'PTR_l_017', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Africabio NPC', 'RP Goldes', 'PTR_l_009', 'Pretoria ');
INSERT INTO `all clients` VALUES ('African World Heritage Fund', 'Kallen S.', 'SNH_l_090', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Agence Francaise De Developpment Project Preparation and Feasibility Studies', 'Kallen S.', 'SNH_l_023', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Agulhas Wetlands', 'Kallen S.', 'SNH_l_075', 'Johannesburg');
INSERT INTO `all clients` VALUES ('ALBERANTE-RANDHART STEERING COMMITTEE (SECT 21)', 'J de Viliers', 'EGT_l_040', 'Alberton');
INSERT INTO `all clients` VALUES ('ALBERTON TUISTE VIR BEJAARDES', 'IJ de Villiers', 'EGT_l_060', 'Alberton');
INSERT INTO `all clients` VALUES ('ALBERTON TUISTE VIR BEJAARDES (ASSOCIATION INC UNDER SECTION 21)', 'IJ de Villiers', 'EGT_l_061', 'Alberton');
INSERT INTO `all clients` VALUES ('Albou Trust', 'H Lotter', 'PTR_l_011', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Albou Trust', 'H Lotter', 'PTR_l_013', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Alchemist House (Pty) Ltd T/A Fleet Connect', 'Mungofa B.', 'SNH_l_021', 'Johannesburg');
INSERT INTO `all clients` VALUES ('AL-CLAD INTERIOR SYSTEMS (PTY) LTD', 'J de Viliers', 'EGT_h_007', 'Alberton');
INSERT INTO `all clients` VALUES ('Altamonte Investments (Pty) Ltd', 'M.A.Motala', 'DBN_l_013', 'Durban');
INSERT INTO `all clients` VALUES ('Amada Asset Management (Pty) Ltd', 'RP Goldes', 'PTR_h_006', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Anglo Inyosi Coal Community Development Trust', 'Muzarewetu N.', 'SNH_l_102', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Apparel Industries (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_019', 'Durban');
INSERT INTO `all clients` VALUES ('Aquarella Investments 224 (Pty) Ltd', 'Y.M Paruk', 'DBN_l_037', 'Durban');
INSERT INTO `all clients` VALUES ('Araf Industries (Pty) Ltd 2016', 'Y.M Paruk', 'DBN_h_003', 'Durban');
INSERT INTO `all clients` VALUES ('Araf Industries (Pty) Ltd 2017', 'Y.M Paruk', 'DBN_h_004', 'Durban');
INSERT INTO `all clients` VALUES ('Argon Securities', 'Kallen S.', 'SNH_l_049', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Asmall & Sons (Pty) Ltd', 'M.A Motala', 'DBN_h_019', 'Durban');
INSERT INTO `all clients` VALUES ('Attacq Group ESD (Pty) Ltd', 'RP Goldes', 'PTR_l_031', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Auditor General Work- contracted out- Umgeni water', 'M.A Motala', 'DBN_h_001', 'Durban');
INSERT INTO `all clients` VALUES ('Autumn Star Trading 100 (Pty) Ltd', 'Y.M Paruk', 'DBN_l_006', 'Durban');
INSERT INTO `all clients` VALUES ('Basadi Ba Kopane Investment (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_103', 'Johannesburg');
INSERT INTO `all clients` VALUES ('BEAUFORT WEST MUSEUM', 'Amaanullah Ayub', 'CTN_h_004', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Bekker Prokureurs', 'RP Goldes', 'PTR_h_011', 'Pretoria ');
INSERT INTO `all clients` VALUES ('BELHAR ISLAMIC PRIMARY SCHOOL', 'Amaanullah Ayub', 'CTN_l_021', 'Cape Town ');
INSERT INTO `all clients` VALUES ('BESSEMER AFRICA (PTY) LTD', 'S Prinsloo', 'EGT_l_024', 'Alberton');
INSERT INTO `all clients` VALUES ('BESSEMER BELANGE (PTY) LTD', 'S Prinsloo', 'EGT_l_025', 'Alberton');
INSERT INTO `all clients` VALUES ('Biarritz Investments (Pty) Ltd', 'Y.M Paruk', 'DBN_l_021', 'Durban');
INSERT INTO `all clients` VALUES ('Bizhub Highveld Lions', 'Muzarewetu N.', 'SNH_l_113', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Blue Shirt Bakery (Pty) Ltd', 'IJ de Villiers', 'EGT_l_015', 'Alberton');
INSERT INTO `all clients` VALUES ('BODY CORPORATE HILLBROW COMMUNITY CENTRE', 'IJ de Villiers', 'EGT_l_055', 'Alberton');
INSERT INTO `all clients` VALUES ('BODY CORPORATE THE BALINESE', 'IJ de Villiers', 'EGT_l_056', 'Alberton');
INSERT INTO `all clients` VALUES ('BOLAND CRICKET BOARD', 'Amaanullah Ayub', 'CTN_l_019', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Borbartia (Pty) Ltd', 'Kallen S.', 'SNH_l_026', 'Johannesburg');
INSERT INTO `all clients` VALUES ('BREDASDORP MUSEUM', 'Amaanullah Ayub', 'CTN_h_006', 'Cape Town ');
INSERT INTO `all clients` VALUES ('CARBONADO ENERGY (PTY) LTD', 'Amaanullah Ayub', 'CTN_h_008', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Casa Luigi Properties (Pty) Ltd', 'Kallen S.', 'SNH_l_027', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Casa Mia Body Corporate', 'RP Goldes', 'PTR_l_039', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Centaur De Roodepoort ', 'Kallen S.', 'SNH_l_089', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Centaur Mining South Africa ', 'Kallen S.', 'SNH_l_088', 'Johannesburg');
INSERT INTO `all clients` VALUES ('CENTRAL AFRICAN ROAD SERVICES (PTY) LTD', 'J de Viliers', 'EGT_l_001', 'Alberton');
INSERT INTO `all clients` VALUES ('Central Cricket Franchise (Pty) Ltd', 'Julia van Wyk', 'BLM_l_003', 'Bloemfontein');
INSERT INTO `all clients` VALUES ('CENTRAL GAUTENG GYMNASTICS ASSOCIATION', 'J de Viliers', 'EGT_l_041', 'Alberton');
INSERT INTO `all clients` VALUES ('CHAFEKER & SHABODIEN INC', 'Amaanullah Ayub', 'CTN_h_016', 'Cape Town ');
INSERT INTO `all clients` VALUES ('CHRISTELIKE MAATSKAPLIKE RAAD ALBERTON', 'IJ de Villiers', 'EGT_l_037', 'Alberton');
INSERT INTO `all clients` VALUES ('CHRISTELIKE MAATSKAPLIKE RAAD STANDERTON', 'IJ de Villiers', 'EGT_l_033', 'Alberton');
INSERT INTO `all clients` VALUES ('Cilbar and Company', 'Y.M Paruk', 'DBN_l_009', 'Durban');
INSERT INTO `all clients` VALUES ('COMMERCIAL MINING WEARPARTS (PTY) LTD', 'J de Viliers', 'EGT_l_008', 'Alberton');
INSERT INTO `all clients` VALUES ('Cricket South Africa', 'Masasa T.', 'SNH_h_004', 'Johannesburg');
INSERT INTO `all clients` VALUES ('C-Track SA (Pty) Limited', 'Mungofa B.', 'SNH_h_005', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Darnall Motor Transport (Pty) Ltd', 'Y.M Paruk', 'DBN_l_016', 'Durban');
INSERT INTO `all clients` VALUES ('DE VRIES INCORPORATED', 'S Prinsloo', 'EGT_h_008', 'Alberton');
INSERT INTO `all clients` VALUES ('Dealernet (Pty) Ltd', 'H Lotter', 'PTR_h_002', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Dealfin (Pty) Ltd', 'H Lotter', 'PTR_h_007', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Debbie Pillay Attorneys', 'J. Jamal', 'DBN_h_015', 'Durban');
INSERT INTO `all clients` VALUES ('Desert Star Trading 109 (Pty) Ltd', 'Y.M Paruk', 'DBN_l_045', 'Durban');
INSERT INTO `all clients` VALUES ('Development Bank of South Africa', 'Kallen S.', 'SNH_h_002', 'Johannesburg');
INSERT INTO `all clients` VALUES ('DIE CHRISTELIKE MAATSKAPLIKE RAAD RING VAN HEIDELBERG', 'IJ de Villiers', 'EGT_l_054', 'Alberton');
INSERT INTO `all clients` VALUES ('DigiCore Electronics (Pty) Ltd', 'Mungofa B.', 'SNH_l_015', 'Johannesburg');
INSERT INTO `all clients` VALUES ('DigiCore Financial Services (Pty) Ltd ', 'Mungofa B.', 'SNH_l_017', 'Johannesburg');
INSERT INTO `all clients` VALUES ('DigiCore Fleet Management SA (Pty) Ltd', 'Mungofa B.', 'SNH_l_016', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Digicore Holdings Limited', 'Mungofa B.', 'SNH_h_015', 'Johannesburg');
INSERT INTO `all clients` VALUES ('DigiCore Management Services (Pty) Ltd', 'Mungofa B.', 'SNH_l_020', 'Johannesburg');
INSERT INTO `all clients` VALUES ('DigiCore Properties (Pty) Ltd ', 'Mungofa B.', 'SNH_l_018', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Dr Alberts, Bouwer & Jordaan Incorporated', 'H Lotter', 'PTR_l_005', 'Pretoria ');
INSERT INTO `all clients` VALUES ('DRIES VAN DER WALT FINANSIELE DIENSTE', 'IJ de Villiers', 'EGT_l_042', 'Alberton');
INSERT INTO `all clients` VALUES ('Drs Thomson Brittain and Partners', 'H Lotter', 'PTR_l_016', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Drs Thomson Brittain and Partners', 'H Lotter', 'PTR_l_028', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Dusty Moon Investments 43 (Pty) Ltd', 'H Lotter', 'PTR_l_032', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Dusty Moon Investments 43 (Pty) Ltd', 'H Lotter', 'PTR_l_033', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Eastern Cricket', 'Muzarewetu N.', 'SNH_l_108', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Easy Vortex Financial Wellness (Pty) Ltd', 'IJ de Villiers', 'EGT_l_014', 'Alberton');
INSERT INTO `all clients` VALUES ('EC- WFtC- Addo National Park - Woody Section (15/18)', 'Kallen S.', 'SNH_l_085', 'Johannesburg');
INSERT INTO `all clients` VALUES ('EKHAYA NEIGHBURHOOD CITY IMPROVEMENT DISTRICT (SECT 21)', 'IJ de Villiers', 'EGT_l_045', 'Alberton');
INSERT INTO `all clients` VALUES ('Environmental Monitors 2016 / 19', 'Kallen S.', 'SNH_l_079', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Etana Holdings', 'Kallen S.', 'SNH_l_041', 'Johannesburg');
INSERT INTO `all clients` VALUES ('F.H. Ali - Business account', 'J. Jamal', 'DBN_h_014', 'Durban');
INSERT INTO `all clients` VALUES ('F.H. Ali - Estate Agent Trust Account - dormant', 'J. Jamal', 'DBN_h_016', 'Durban');
INSERT INTO `all clients` VALUES ('Factodex (Pty) Ltd', 'Y.M Paruk', 'DBN_l_001', 'Durban');
INSERT INTO `all clients` VALUES ('Fashion Fusion Distribution (Pty) Ltd', 'F.A.S Haffejee', 'DBN_h_018', 'Durban');
INSERT INTO `all clients` VALUES ('Fashion Fusion Traders (Pty) Ltd', 'F.A.S Haffejee', 'DBN_h_002', 'Durban');
INSERT INTO `all clients` VALUES ('Firebush Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_028', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Firewood Investments (Pty) Ltd', 'M.A.Motala', 'DBN_l_014', 'Durban');
INSERT INTO `all clients` VALUES ('Fivaz Incorporated', 'RP Goldes', 'PTR_h_004', 'Pretoria ');
INSERT INTO `all clients` VALUES ('FONTAINEBLEAU GEMEENSKAPSKERK', 'IJ de Villiers', 'EGT_l_019', 'Alberton');
INSERT INTO `all clients` VALUES ('Free State Cricket NPC', 'Julia van Wyk', 'BLM_l_001', 'Bloemfontein');
INSERT INTO `all clients` VALUES ('Freedom Stationery (Pty) Ltd', 'M. Haffejee', 'DBN_h_020', 'Durban');
INSERT INTO `all clients` VALUES ('Friedshelf 1571 (Pty) Ltd', 'Kallen S.', 'SNH_l_029', 'Johannesburg');
INSERT INTO `all clients` VALUES ('GALAXY JUWELERS (PTY) LTD', 'J de Viliers', 'EGT_h_004', 'Alberton');
INSERT INTO `all clients` VALUES ('GANGEN ATTORNEYS', 'Amaanullah Ayub', 'CTN_h_017', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Gauteng Cricket Board', 'Muzarewetu N.', 'SNH_l_110', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Gayatri Cans (Pty) Ltd ', 'Kallen S.', 'SNH_h_023', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Gayatri Cans (Pty) Ltd ', 'Kallen S.', 'SNH_h_025', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Gayatri Paper Mill (Pty) Ltd ', 'Kallen S.', 'SNH_h_017', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Gayatri Paper Mill (Pty) Ltd ', 'Kallen S.', 'SNH_h_018', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Gayatri Paper Mill Gauteng (Pty) Ltd  ', 'Kallen S.', 'SNH_l_053', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Gayatri Paper Mill Gauteng (Pty) Ltd  ', 'Kallen S.', 'SNH_l_056', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Golden Era Printers & Stationers Bops (Pty) Ltd ', 'Kallen S.', 'SNH_h_011', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Golden Era Printers & Stationers Bops (Pty) Ltd ', 'Kallen S.', 'SNH_h_012', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Golden Gate Higlands National Park  Working for Wetlands', 'Kallen S.', 'SNH_l_077', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Greene Consulting Engineers (Pty) Ltd', 'RP Goldes', 'PTR_l_008', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Griqua Diamonds (Pty) Ltd t/a Northern Cape Cricket (Pty) Ltd', 'Julia van Wyk', 'BLM_l_002', 'Bloemfontein');
INSERT INTO `all clients` VALUES ('Ground Lily Investments (Pty) Ltd ', 'Kallen S.', 'SNH_l_030', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Haupt Earle & Vennote Attorneys', 'RP Goldes', 'PTR_h_010', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Hazsons Holdings Shareblock (Pty) Ltd', 'J. Jamal', 'DBN_l_002', 'Durban');
INSERT INTO `all clients` VALUES ('Hiconnex (Pty) Ltd', 'H Lotter', 'PTR_l_001', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Hiconnex Communications (Pty) Ltd', 'Helga Lotter', 'PTR_l_014', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Hiconnex Industrials (Pty) Ltd', 'Helga Lotter', 'PTR_l_015', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Highgrowth Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_042', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Hollard Behold (Cresta Properties) (Pty) Ltd', 'Kallen S.', 'SNH_l_044', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Hollard Business Associates (Pty) Ltd', 'Kallen S.', 'SNH_l_043', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Hollard Dealer Partners (Pty) Ltd', 'Kallen S.', 'SNH_l_039', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Hollard Investment Managers (Pty) Ltd', 'Kallen S.', 'SNH_l_031', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Hollard Life Properties (Pty) Ltd ', 'Kallen S.', 'SNH_l_032', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Hollard Portfolio (Pty) Ltd', 'Kallen S.', 'SNH_l_048', 'Johannesburg');
INSERT INTO `all clients` VALUES ('HUGUENOT MEMORIAL MUSEUM', 'Amaanullah Ayub', 'CTN_h_003', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Hussun Goga & Company Attorney', 'Y.M Paruk', 'DBN_h_007', 'Durban');
INSERT INTO `all clients` VALUES ('Ice Blue Clothing (Pty) Ltd', 'Y.M Paruk', 'DBN_l_012', 'Durban');
INSERT INTO `all clients` VALUES ('Independent Power Producer office', 'Kallen S.', 'SNH_l_057', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Industrial Parks Revitalisation Programme (DTI)', 'Kallen S.', 'SNH_l_024', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Integrated Fare Collection Services (Pty) Ltd ', 'Mungofa B.', 'SNH_l_019', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Intekom', 'Mungofa B.', 'SNH_l_010', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Irfan Trading', 'F.A.S Haffejee', 'DBN_l_025', 'Durban');
INSERT INTO `all clients` VALUES ('Islamic Guidance Trust ', 'R.Timol', 'DBN_l_042', 'Durban');
INSERT INTO `all clients` VALUES ('Izingwe Aberdare Cables (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_092', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe Cable Investments (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_093', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe Capital (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_105', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe Holdings (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_097', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe International Fund (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_094', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe Investment Holdings (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_098', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe Main Street (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_095', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe Properties (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_091', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Izingwe Property Managers (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_096', 'Johannesburg');
INSERT INTO `all clients` VALUES ('J AND K INTERIORS (PTY) LTD', 'Amaanullah Ayub', 'CTN_l_024', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Jannie Parsons Future Financials (Pty) Ltd', 'RP Goldes', 'PTR_h_003', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Jarvis Jacobs Raubenheimer Inc - Trust Audit', 'RP Goldes', 'PTR_h_005', 'Pretoria ');
INSERT INTO `all clients` VALUES ('JOSCHO-MADULAMOHO JOINT VENTRUE', 'IJ de Villiers', 'EGT_l_028', 'Alberton');
INSERT INTO `all clients` VALUES ('Jyotland Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_064', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Kalbo Land Holdings (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_029', 'Durban');
INSERT INTO `all clients` VALUES ('Kamiesberg Working for Wetlands', 'Kallen S.', 'SNH_l_074', 'Johannesburg');
INSERT INTO `all clients` VALUES ('KHUSEL \'NDALO SOUTH AFRICA NPC', 'Amaanullah Ayub', 'CTN_l_004', 'Cape Town ');
INSERT INTO `all clients` VALUES ('KHUSEL \'NDALO SOUTH AFRICA NPC DAC PROJECT 1', 'Amaanullah Ayub', 'CTN_l_009', 'Cape Town ');
INSERT INTO `all clients` VALUES ('KHUSEL \'NDALO SOUTH AFRICA NPC DAC PROJECT 2', 'Amaanullah Ayub', 'CTN_l_011', 'Cape Town ');
INSERT INTO `all clients` VALUES ('KHUSEL \'NDALO SOUTH AFRICA NPC DAC PROJECT 3', 'Amaanullah Ayub', 'CTN_l_012', 'Cape Town ');
INSERT INTO `all clients` VALUES ('KNP WORKING FOR WETLAND', 'Kallen S.', 'SNH_l_078', 'Johannesburg');
INSERT INTO `all clients` VALUES ('KUSAGA TAKA CONSULTING', 'Amaanullah Ayub', 'CTN_l_002', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Kwa Dukuza Resource Centre NPC', 'J. Jamal', 'DBN_l_039', 'Durban');
INSERT INTO `all clients` VALUES ('Kwazulu- Natal Cricket Union', 'M. Haffejee', 'DBN_l_017', 'Durban');
INSERT INTO `all clients` VALUES ('Kwazulu Natal Cricket Union Bursary Trust', 'M. Haffejee', 'DBN_l_015', 'Durban');
INSERT INTO `all clients` VALUES ('KZN Cricket (Pty) Ltd', 'M. Haffejee', 'DBN_h_006', 'Durban');
INSERT INTO `all clients` VALUES ('L & J Finance (Pty) Ltd', 'Kallen S.', 'SNH_l_065', 'Johannesburg');
INSERT INTO `all clients` VALUES ('LAERSKOOL GENERAAL ALBERTS', 'J de Viliers', 'EGT_l_020', 'Alberton');
INSERT INTO `all clients` VALUES ('Laeveld Agrochem (Pty) Ltd and its Subsidiaries', 'RP Goldes', 'PTR_h_001', 'Pretoria ');
INSERT INTO `all clients` VALUES ('LAFARGE COMMUNITY TRUST', 'IJ de Villiers', 'EGT_l_062', 'Alberton');
INSERT INTO `all clients` VALUES ('LAFARGE EDUCATION TRUST', 'IJ de Villiers', 'EGT_l_016', 'Alberton');
INSERT INTO `all clients` VALUES ('LAMARA HENDRICKS ATTORNEYS', 'Amaanullah Ayub', 'CTN_h_015', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Laxmi Trust & Investment (Lenasia) (Pty) Ltd', 'Kallen S.', 'SNH_l_066', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Laxmi Trust & Investment Company', 'Kallen S.', 'SNH_l_063', 'Johannesburg');
INSERT INTO `all clients` VALUES ('LEHLOHONOLO PROPERITIES', 'IJ de Villiers', 'EGT_h_013', 'Alberton');
INSERT INTO `all clients` VALUES ('Leungo Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_047', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Lexshell 627 Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_069', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Limpopo Department of Health Programme (DBSA Mandate)', 'Kallen S.', 'SNH_l_022', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Limpopo Impala Cricket Union (NPC)', 'Kallen S.', 'SNH_l_071', 'Johannesburg');
INSERT INTO `all clients` VALUES ('LUTHERON COMMUNITY OUTREACH FOUNDATION', 'IJ de Villiers', 'EGT_l_021', 'Alberton');
INSERT INTO `all clients` VALUES ('Lynnwood Bridge Property Owners Association NPC', 'RP Goldes', 'PTR_l_019', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Lynnwood Bridge Property Owners Association NPC', 'RP Goldes', 'PTR_l_029', 'Pretoria ');
INSERT INTO `all clients` VALUES ('M.S Omar and Associates', 'R. Timol', 'DBN_h_010', 'Durban');
INSERT INTO `all clients` VALUES ('MADULAMMOHO HOUSING ASSOCIATION NPC', 'IJ de Villiers', 'EGT_h_006', 'Alberton');
INSERT INTO `all clients` VALUES ('MAESTRO BEHUISING (PTY) LTD', 'S Prinsloo', 'EGT_l_044', 'Alberton');
INSERT INTO `all clients` VALUES ('Magnolia Ridge Properties 102 (Pty) Ltd', 'Y.M Paruk', 'DBN_l_044', 'Durban');
INSERT INTO `all clients` VALUES ('Mapungubwe National Park  Working for Wetlands', 'Kallen S.', 'SNH_l_076', 'Johannesburg');
INSERT INTO `all clients` VALUES ('MASSEL PROPERTY SERVICES (PTY) LTD', 'S Prinsloo', 'EGT_l_009', 'Alberton');
INSERT INTO `all clients` VALUES ('Massmart Supplier Development Fund (Massmart SDF)', 'Masasa T.', 'SNH_l_009', 'Johannesburg');
INSERT INTO `all clients` VALUES ('MAYAT NURICK LANGA INC', 'J de Villiers', 'EGT_h_009', 'Alberton');
INSERT INTO `all clients` VALUES ('McIver Apparel (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_020', 'Durban');
INSERT INTO `all clients` VALUES ('MES KHULA SUSTAINABILITY TRUST', 'IJ de Villiers', 'EGT_l_059', 'Alberton');
INSERT INTO `all clients` VALUES ('Metal and Engineering Industries Bargaining Council Sick Pay Fund', 'Kallen S.', 'SNH_h_008', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Metal and Engineering Industries Permanent Disability Scheme', 'Kallen S.', 'SNH_h_006', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Metal industries Benefit Fund Administrators', 'Kallen S.', 'SNH_h_009', 'Johannesburg');
INSERT INTO `all clients` VALUES ('METRO EVANGELIESE SORG (SECTION 21)', 'IJ de Villiers', 'EGT_l_004', 'Alberton');
INSERT INTO `all clients` VALUES ('MIDVAAL THREADING (PTY) LTD', 'S Prinsloo', 'EGT_l_017', 'Alberton');
INSERT INTO `all clients` VALUES ('Mogwele Waste (Pty) Ltd ', 'Kallen S.', 'SNH_h_016', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Mogwele Waste (Pty) Ltd ', 'Amaanullah Ayub', 'CTN_h_001', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Mohammed Motala and Company', 'Y.M Paruk', 'DBN_h_011', 'Durban');
INSERT INTO `all clients` VALUES ('Molsons Property Investments (Pty) Ltd ', 'Y.M Paruk', 'DBN_l_004', 'Durban');
INSERT INTO `all clients` VALUES ('Monyetla', 'Masasa T.', 'SNH_l_002', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Morgan Pillay, Reddy and Company', 'Y.M Paruk', 'DBN_h_012', 'Durban');
INSERT INTO `all clients` VALUES ('Morning Tide Investments 67 (Pty) Ltd', 'Y.M Paruk', 'DBN_l_043', 'Durban');
INSERT INTO `all clients` VALUES ('Moss Ridge Properties (Pty) Ltd', 'M. Haffejee', 'DBN_h_023', 'Durban');
INSERT INTO `all clients` VALUES ('Mountain Cypress (Pty) Ltd', 'Kallen S.', 'SNH_l_033', 'Johannesburg');
INSERT INTO `all clients` VALUES ('MP- Ecosystem Rehabilitation and Fencing of Nature Reserve', 'Kallen S.', 'SNH_l_082', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Mpumalanga Cricket Union (NPC)', 'Kallen S.', 'SNH_l_072', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Mtha Financial Services Trust', 'Muzarewetu N.', 'SNH_l_100', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Mtha We Mpumelelo Investments (Pty) Ltd', 'Muzarewetu N.', 'SNH_l_099', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Multiply Titans', 'Muzarewetu N.', 'SNH_l_112', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Mystar Education and Bussiness solution (Pty) Ltd', 'J de Viliers', 'EGT_l_018', 'Alberton');
INSERT INTO `all clients` VALUES ('N G BARMHARTIGHEIDSDIENS (NGBD) - {NEW NAME - TUTELA}', 'IJ de Villiers', 'EGT_l_011', 'Alberton');
INSERT INTO `all clients` VALUES ('N G BARMHARTIGHEIDSDIENS MPUMALANGA', 'IJ de Villiers', 'EGT_l_058', 'Alberton');
INSERT INTO `all clients` VALUES ('N G GEMEENTE LAMBTON', 'IJ de Villiers', 'EGT_l_046', 'Alberton');
INSERT INTO `all clients` VALUES ('N G KERK AASVOELKOP', 'IJ de Villiers', 'EGT_l_047', 'Alberton');
INSERT INTO `all clients` VALUES ('N G KERK ELSBURG', 'IJ de Villiers', 'EGT_l_049', 'Alberton');
INSERT INTO `all clients` VALUES ('N G KERK ELSBURG SUID', 'IJ de Villiers', 'EGT_l_048', 'Alberton');
INSERT INTO `all clients` VALUES ('N G KERK ELSPARK', 'IJ de Villiers', 'EGT_l_053', 'Alberton');
INSERT INTO `all clients` VALUES ('NATIONAL ASSOCIATION OF SOCIAL HOUSING ORGANISATION', 'IJ de Villiers', 'EGT_l_034', 'Alberton');
INSERT INTO `all clients` VALUES ('NC-WftC Namaqua National Park (15/18)', 'Kallen S.', 'SNH_l_083', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Nectatype', 'Masasa T.', 'SNH_l_006', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Berea Centre (Pty) Ltd', 'Kallen S.', 'SNH_l_045', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Era Labels (Bop) (Pty) Ltd ', 'Kallen S.', 'SNH_l_054', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Era Labels (Bop) (Pty) Ltd  ', 'Kallen S.', 'SNH_l_051', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Era P.P. Sacks (Bop) (Pty) Ltd ', 'Kallen S.', 'SNH_h_026', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Era Packaging Bops (Pty) Ltd ', 'Kallen S.', 'SNH_h_010', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Era Packaging Bops (Pty) Ltd ', 'Kallen S.', 'SNH_h_013', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Era Paper Bags Manufacturers Bops (Pty) Ltd', 'Amaanullah Ayub', 'CTN_h_013', 'Cape Town ');
INSERT INTO `all clients` VALUES ('New Era Paper Bags Manufacturers Bops (Pty) Ltd ', 'Kallen S.', 'SNH_h_021', 'Johannesburg');
INSERT INTO `all clients` VALUES ('New Era PP Sacks BOP (Pty) Ltd.', 'Amaanullah Ayub', 'CTN_h_011', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Newshelf 33 (Pty) Ltd ', 'Kallen S.', 'SNH_l_034', 'Johannesburg');
INSERT INTO `all clients` VALUES ('NG GEMEENTE SUNWARDPARK', 'IJ de Villiers', 'EGT_l_051', 'Alberton');
INSERT INTO `all clients` VALUES ('NG Kerk Faerie Glen', 'RP Goldes', 'PTR_l_036', 'Pretoria ');
INSERT INTO `all clients` VALUES ('NG KERK SINODE HOeVELD', 'IJ de Villiers', 'EGT_l_007', 'Alberton');
INSERT INTO `all clients` VALUES ('Nirvana Investments (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_030', 'Durban');
INSERT INTO `all clients` VALUES ('North West Cricket', 'Muzarewetu N.', 'SNH_l_111', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Northerns Cricket', 'Muzarewetu N.', 'SNH_l_109', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Novo And Comu Joint Venture (Pty)Ltd', 'RP Goldes', 'PTR_l_007', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Energy (Pty) Ltd', 'RP Goldes', 'PTR_l_003', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Energy (Pty) Ltd', 'RP Goldes', 'PTR_l_004', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Kew (Pty) Ltd', 'RP Goldes', 'PTR_l_020', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Kew (Pty) Ltd', 'RP Goldes', 'PTR_l_023', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Lincoln (Pty) Ltd', 'RP Goldes', 'PTR_l_021', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Lincoln (Pty) Ltd', 'RP Goldes', 'PTR_l_024', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Mcfarlane (Pty) Ltd', 'RP Goldes', 'PTR_l_022', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Novo Mcfarlane (Pty) Ltd', 'RP Goldes', 'PTR_l_025', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Nu Laxmi Selections (Pty) Ltd', 'Kallen S.', 'SNH_l_061', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Nu-Laxmi Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_060', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Nu-Laxmi Leasing (Pty) Ltd', 'Kallen S.', 'SNH_l_062', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Nuprof Investments (Pty) Ltd', 'Y.M Paruk', 'DBN_l_034', 'Durban');
INSERT INTO `all clients` VALUES ('OLD HARBOUR MUSEUM', 'Amaanullah Ayub', 'CTN_h_005', 'Cape Town ');
INSERT INTO `all clients` VALUES ('OLOF PALME INTERNATIONAL CENTRE - Projects', 'Amaanullah Ayub', 'CTN_l_001', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Ombudsman for Banking Services', 'Muzarewetu N.', 'SNH_l_104', 'Johannesburg');
INSERT INTO `all clients` VALUES ('One Call Properties CC', 'RP Goldes', 'PTR_h_009', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Opium Investments (Pty) Ltd', 'Y.M Paruk', 'DBN_l_022', 'Durban');
INSERT INTO `all clients` VALUES ('Orient Islamic School', 'Y.M Paruk', 'DBN_l_028', 'Durban');
INSERT INTO `all clients` VALUES ('Oyster Plastics (Pty) Ltd', 'M. Haffejee', 'DBN_h_021', 'Durban');
INSERT INTO `all clients` VALUES ('Paramax Clothing (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_026', 'Durban');
INSERT INTO `all clients` VALUES ('PARAMOUNT TRAILERS (PTY) LTD', 'J de Viliers', 'EGT_h_005', 'Alberton');
INSERT INTO `all clients` VALUES ('Paruk\'s Corporate Enterprises (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_036', 'Durban');
INSERT INTO `all clients` VALUES ('Petroprt N3 Heidelberg (Pty) Ltd', 'Kallen S.', 'SNH_l_070', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Pico Ruivo (Pty) Ltd', 'Kallen S.', 'SNH_l_035', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Plan B Financial Compliance (Pty) Ltd', 'Kallen S.', 'SNH_l_046', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Platinum High Tech Park Development (Pty) Ltd', 'RP Goldes', 'PTR_l_012', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Pravda and Knowles Attorneys', 'Y.M Paruk', 'DBN_h_008', 'Durban');
INSERT INTO `all clients` VALUES ('Pretoria Box Manufacturers Joint Venture ', 'RP Goldes', 'PTR_l_002', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Pretoria Woman\'s 10km Race NPC', 'RP Goldes', 'PTR_l_034', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Pretoria Woman\'s 10km Race NPC', 'RP Goldes', 'PTR_l_035', 'Pretoria ');
INSERT INTO `all clients` VALUES ('PRIDE MILLING COMPANY (PTY) LTD', 'S Prinsloo', 'EGT_h_002', 'Alberton');
INSERT INTO `all clients` VALUES ('Prime Stores (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_046', 'Durban');
INSERT INTO `all clients` VALUES ('PRO EKKLESIA NPC', 'IJ de Villiers', 'EGT_l_026', 'Alberton');
INSERT INTO `all clients` VALUES ('Prowgrowth Investment', 'Y.M Paruk', 'DBN_l_031', 'Durban');
INSERT INTO `all clients` VALUES ('Pybus Thirty-Fourty (Pty) Ltd', 'Kallen S.', 'SNH_l_068', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Qhakaza AMPS (Pty) Ltd', 'Mungofa B.', 'SNH_l_014', 'Johannesburg');
INSERT INTO `all clients` VALUES ('RATES WATCH (PTY) LTD', 'S Prinsloo', 'EGT_l_012', 'Alberton');
INSERT INTO `all clients` VALUES ('Real Tree Trading 1 (Pty) Ltd', 'Masasa T.', 'SNH_h_014', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Reprographics', 'Masasa T.', 'SNH_l_008', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Richard Cawood Properties (Pty) Ltd', 'RP Goldes', 'PTR_h_008', 'Pretoria ');
INSERT INTO `all clients` VALUES ('RIDGE PROPERTIES (PTY) LTD', 'J de Viliers', 'EGT_l_023', 'Alberton');
INSERT INTO `all clients` VALUES ('RUBATO TRUST', 'Amaanullah Ayub', 'CTN_l_025', 'Cape Town ');
INSERT INTO `all clients` VALUES ('RUSTIVIA INDUSTRIAL ESTATES (PTY) LTD', 'J de Viliers', 'EGT_l_032', 'Alberton');
INSERT INTO `all clients` VALUES ('S A TIMBER (WELKOM) (PTY) LTD', 'S Prinsloo', 'EGT_l_038', 'Alberton');
INSERT INTO `all clients` VALUES ('S A TIMBER AND JOINERY WORKS (PTY) LTD', 'S Prinsloo', 'EGT_l_039', 'Alberton');
INSERT INTO `all clients` VALUES ('SA Coal Mining Holdings Limited', 'Muzarewetu N.', 'SNH_l_106', 'Johannesburg');
INSERT INTO `all clients` VALUES ('SA Innovation Summit (Pty)Ltd', 'RP Goldes', 'PTR_l_018', 'Pretoria ');
INSERT INTO `all clients` VALUES ('SA TIMBER (KROONSTAD) (PTY) LTD', 'S Prinsloo', 'EGT_l_030', 'Alberton');
INSERT INTO `all clients` VALUES ('SA TIMBER (VIRGINIA) (PTY) LTD', 'S Prinsloo', 'EGT_l_031', 'Alberton');
INSERT INTO `all clients` VALUES ('SADC LAWYERS ASSOCIATION NPC', 'IJ de Villiers', 'EGT_l_010', 'Alberton');
INSERT INTO `all clients` VALUES ('Safdev Holdings (Pty) Ltd', 'RP Goldes', 'PTR_l_006', 'Pretoria ');
INSERT INTO `all clients` VALUES ('SAICA Pension Fund', 'Kallen S.', 'SNH_h_022', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Sand Olive (Pty) Ltd', 'Kallen S.', 'SNH_l_036', 'Johannesburg');
INSERT INTO `all clients` VALUES ('SANParks Natural Resource Projects', 'Kallen S.', 'SNH_l_073', 'Johannesburg');
INSERT INTO `all clients` VALUES ('SATIM (O F S) (PTY) LTD', 'S Prinsloo', 'EGT_l_029', 'Alberton');
INSERT INTO `all clients` VALUES ('SAVECOMM PROPERTIES CC', 'IJ de Villiers', 'EGT_h_011', 'Alberton');
INSERT INTO `all clients` VALUES ('Scandura Trading (Pty) Ltd', 'Y.M Paruk', 'DBN_l_010', 'Durban');
INSERT INTO `all clients` VALUES ('SCHUTTE J H P Mnr', 'IJ de Villiers', 'EGT_h_014', 'Alberton');
INSERT INTO `all clients` VALUES ('Seabiscuit Body Corporate', 'H Lotter', 'PTR_l_038', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Second Street Mall (Pty) Ltd', 'Kallen S.', 'SNH_l_067', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Selvie Pillay and Company', 'J. Jamal', 'DBN_h_013', 'Durban');
INSERT INTO `all clients` VALUES ('Seraps (Pty) Ltd', 'M.A.Motala', 'DBN_l_033', 'Durban');
INSERT INTO `all clients` VALUES ('Shanduka Black Umbrellas', 'Muzarewetu N.', 'SNH_l_107', 'Johannesburg');
INSERT INTO `all clients` VALUES ('SILVER PARK SELF STORAGE (PTY) LTD', 'Amaanullah Ayub', 'CTN_l_015', 'Cape Town ');
INSERT INTO `all clients` VALUES ('SILVERY SUN ENERGY INVESTMENTS (PTY) LTD', 'Amaanullah Ayub', 'CTN_l_016', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Sinayo Securities (Pty) Ltd', 'Kallen S.', 'SNH_l_050', 'Johannesburg');
INSERT INTO `all clients` VALUES ('SONYA MEISTRE INCORPORATED', 'J de Viliers', 'EGT_h_010', 'Alberton');
INSERT INTO `all clients` VALUES ('SOS CHILDREN\'S VILLAGE ASSOCIATION OF RAS (NATIONAL)', 'J de Viliers', 'EGT_h_003', 'Alberton');
INSERT INTO `all clients` VALUES ('SOS KINDERDORP INTERNATIONAL SOUTHERN AFRICAN REGION', 'J de Viliers', 'EGT_l_003', 'Alberton');
INSERT INTO `all clients` VALUES ('South African Airways Technical (SAAT)', 'Muzarewetu N.', 'SNH_h_003', 'Johannesburg');
INSERT INTO `all clients` VALUES ('SOUTH AFRICAN BOOK DEVELOPMENT COUNCIL NPC', 'Amaanullah Ayub', 'CTN_l_005', 'Cape Town ');
INSERT INTO `all clients` VALUES ('South African File Manufacturers (Pty) Ltd', 'M. Haffejee', 'DBN_h_022', 'Durban');
INSERT INTO `all clients` VALUES ('South African Institute of Financial Markets', 'RP Goldes', 'PTR_l_010', 'Pretoria ');
INSERT INTO `all clients` VALUES ('South African Institute of Financial Markets', 'RP Goldes', 'PTR_l_040', 'Pretoria ');
INSERT INTO `all clients` VALUES ('South African National Halaal Authority', 'Y.M Paruk', 'DBN_l_005', 'Durban');
INSERT INTO `all clients` VALUES ('South African Society of Clinical and Radiation Oncologists', 'H Lotter', 'PTR_l_037', 'Pretoria ');
INSERT INTO `all clients` VALUES ('South African Travel Company (SATC)', 'Masasa T.', 'SNH_h_024', 'Johannesburg');
INSERT INTO `all clients` VALUES ('SOUTH WEST DISTRICT CRICKET COUNCIL', 'Amaanullah Ayub', 'CTN_l_008', 'Cape Town ');
INSERT INTO `all clients` VALUES ('SPIES ABRAHAM MARTHINUS', 'IJ de Villiers', 'EGT_h_012', 'Alberton');
INSERT INTO `all clients` VALUES ('Squadron Trading (Pty) Ltd', 'Y.M Paruk', 'DBN_l_011', 'Durban');
INSERT INTO `all clients` VALUES ('SSI Schaefer Systems', 'Muzarewetu N.', 'SNH_l_101', 'Johannesburg');
INSERT INTO `all clients` VALUES ('STANDER PROKUREURS', 'IJ de Villiers', 'EGT_h_015', 'Alberton');
INSERT INTO `all clients` VALUES ('Stanger and District Association for the Aged', 'J. Jamal', 'DBN_l_032', 'Durban');
INSERT INTO `all clients` VALUES ('Star Schools  (Pty) Ltd', 'J de Viliers', 'EGT_l_052', 'Alberton');
INSERT INTO `all clients` VALUES ('Star Schools High (Pty) Ltd', 'J de Viliers', 'EGT_l_002', 'Alberton');
INSERT INTO `all clients` VALUES ('STEENBOK TRUST 253/88', 'J de Viliers', 'EGT_l_050', 'Alberton');
INSERT INTO `all clients` VALUES ('Striding Edge CC', 'J. Jamal', 'DBN_l_035', 'Durban');
INSERT INTO `all clients` VALUES ('Sucrose Motors and Service Station (Pty) Ltd', 'J. Jamal', 'DBN_l_027', 'Durban');
INSERT INTO `all clients` VALUES ('Swiftnet (Pty) Ltd', 'Mungofa B.', 'SNH_h_007', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Syndicate Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_037', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Syringa Tree Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_038', 'Johannesburg');
INSERT INTO `all clients` VALUES ('TAME COMMUNICATIONS (PTY) LTD', 'J de Viliers', 'EGT_l_036', 'Alberton');
INSERT INTO `all clients` VALUES ('Telkom Benevolent Fund', 'Mungofa B.', 'SNH_l_012', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Telkom Foundation Trust', 'Mungofa B.', 'SNH_l_013', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Telkom SA SOC Limited', 'Mungofa B.', 'SNH_h_001', 'Johannesburg');
INSERT INTO `all clients` VALUES ('TEL-SCREW PRODUCTS (PTY) LTD', 'S Prinsloo', 'EGT_l_005', 'Alberton');
INSERT INTO `all clients` VALUES ('TERAOKA S A (PTY) LTD', 'S Prinsloo', 'EGT_h_001', 'Alberton');
INSERT INTO `all clients` VALUES ('The Attacq Foundation Trust', 'RP Goldes', 'PTR_l_030', 'Pretoria ');
INSERT INTO `all clients` VALUES ('THE HUMAN KIND GROUP (PTY) LTD', 'S Prinsloo', 'EGT_l_013', 'Alberton');
INSERT INTO `all clients` VALUES ('THE KAMBULE TRUST', 'Amaanullah Ayub', 'CTN_l_022', 'Cape Town ');
INSERT INTO `all clients` VALUES ('The Laxmi Group Limited', 'Kallen S.', 'SNH_l_059', 'Johannesburg');
INSERT INTO `all clients` VALUES ('THE MINEWORKERS BENEFICIARY FUND', 'Amaanullah Ayub', 'CTN_h_009', 'Cape Town ');
INSERT INTO `all clients` VALUES ('THE MINEWORKERS TRUST FUND', 'Amaanullah Ayub', 'CTN_h_012', 'Cape Town ');
INSERT INTO `all clients` VALUES ('THE NBC UMBRELLA BENEFICIARY FUND', 'Amaanullah Ayub', 'CTN_h_007', 'Cape Town ');
INSERT INTO `all clients` VALUES ('THE NBC UMBRELLA TRUST', 'Amaanullah Ayub', 'CTN_h_002', 'Cape Town ');
INSERT INTO `all clients` VALUES ('THE RACHELS ANGELS TRUST', 'Amaanullah Ayub', 'CTN_l_013', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Thekwini Reinforcing (Pty) Ltd', 'J. Jamal', 'DBN_h_005', 'Durban');
INSERT INTO `all clients` VALUES ('Timol and Associates', 'Y.M Paruk', 'DBN_h_009', 'Durban');
INSERT INTO `all clients` VALUES ('Titans Cricket', 'Muzarewetu N.', 'SNH_l_114', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Tjokkerville', 'Masasa T.', 'SNH_l_003', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Toufic Trading (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_038', 'Durban');
INSERT INTO `all clients` VALUES ('TrackAN Investments (Pty) Ltd', 'Y.M Paruk', 'DBN_l_003', 'Durban');
INSERT INTO `all clients` VALUES ('TRANS-TECH LOGISTICS (PTY) LTD', 'J de Viliers', 'EGT_l_006', 'Alberton');
INSERT INTO `all clients` VALUES ('TREK TRANSPORT (PTY) LTD', 'S Prinsloo', 'EGT_l_027', 'Alberton');
INSERT INTO `all clients` VALUES ('Triangle Stores (Pty) Ltd', 'F.A.S Haffejee', 'DBN_l_024', 'Durban');
INSERT INTO `all clients` VALUES ('UITKOMS HOME FOR GIRLS', 'IJ de Villiers', 'EGT_l_022', 'Alberton');
INSERT INTO `all clients` VALUES ('UKUKHULA TRUST', 'Amaanullah Ayub', 'CTN_l_023', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Umgeni Water Services SOC Ltd (immaterial subsidery non- trading)', 'M.A Motala', 'DBN_h_017', 'Durban');
INSERT INTO `all clients` VALUES ('Unity Paper Sales (Pty) Ltd ', 'Kallen S.', 'SNH_h_019', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Unity Paper Sales (Pty) Ltd ', 'Kallen S.', 'SNH_h_020', 'Johannesburg');
INSERT INTO `all clients` VALUES ('V G KERK EDENPARK', 'IJ de Villiers', 'EGT_l_043', 'Alberton');
INSERT INTO `all clients` VALUES ('VAN DER ROSS & MOTALA INC', 'Amaanullah Ayub', 'CTN_h_014', 'Cape Town ');
INSERT INTO `all clients` VALUES ('VAN DER WALT CRESCENT ENCLOSURE NPC', 'IJ de Villiers', 'EGT_l_057', 'Alberton');
INSERT INTO `all clients` VALUES ('VASCOBA INVESTMENTS (PTY) LTD', 'S Prinsloo', 'EGT_l_035', 'Alberton');
INSERT INTO `all clients` VALUES ('Vayej Bros (Pty) Ltd', 'Y.M Paruk', 'DBN_l_018', 'Durban');
INSERT INTO `all clients` VALUES ('VCE/Thusong', 'Masasa T.', 'SNH_l_005', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Velvet Raisin Investments (Pty) Ltd', 'Kallen S.', 'SNH_l_040', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Vesco Ecko', 'Masasa T.', 'SNH_l_007', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Vesco Parent', 'Masasa T.', 'SNH_l_004', 'Johannesburg');
INSERT INTO `all clients` VALUES ('VISION CHILD AND YOUTH CENTRE', 'Amaanullah Ayub', 'CTN_l_006', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Vuwa Investments (Pty) Ltd', 'Masasa T.', 'SNH_l_001', 'Johannesburg');
INSERT INTO `all clients` VALUES ('W P PROFESSION CRICKET (PTY) LTD.', 'Amaanullah Ayub', 'CTN_l_010', 'Cape Town ');
INSERT INTO `all clients` VALUES ('WALKERS INCORPORATED', 'Amaanullah Ayub', 'CTN_h_010', 'Cape Town ');
INSERT INTO `all clients` VALUES ('WALKERS INCORPORATED', 'Amaanullah Ayub', 'CTN_l_007', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Waxpak (Pty) Ltd', 'Kallen S.', 'SNH_l_055', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Waxpak (Pty) Ltd', 'Kallen S.', 'SNH_l_052', 'Johannesburg');
INSERT INTO `all clients` VALUES ('WC - Table Mountain National Park - WftC 15/18', 'Kallen S.', 'SNH_l_086', 'Johannesburg');
INSERT INTO `all clients` VALUES ('WC - West Coast National Park', 'Kallen S.', 'SNH_l_080', 'Johannesburg');
INSERT INTO `all clients` VALUES ('WC - WftC Cape Agulhas National Park (15/18)', 'Kallen S.', 'SNH_l_087', 'Johannesburg');
INSERT INTO `all clients` VALUES ('WC WftC GRNP Knysna Section (15/18)', 'Kallen S.', 'SNH_l_081', 'Johannesburg');
INSERT INTO `all clients` VALUES ('WC WftC GRNP Wilderness Section (15/18)', 'Kallen S.', 'SNH_l_084', 'Johannesburg');
INSERT INTO `all clients` VALUES ('WELKOM TRUST', 'Amaanullah Ayub', 'CTN_l_020', 'Cape Town ');
INSERT INTO `all clients` VALUES ('WESTERN CAPE CRICKET (PTY) LTD', 'Amaanullah Ayub', 'CTN_l_017', 'Cape Town ');
INSERT INTO `all clients` VALUES ('WESTERN PROVINCE CRICKET ASSOCIATION', 'Amaanullah Ayub', 'CTN_l_003', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Womens Cultural Group', 'R.Timol', 'DBN_l_041', 'Durban');
INSERT INTO `all clients` VALUES ('Womens Cultural Group Educational Trust', 'R.Timol', 'DBN_l_040', 'Durban');
INSERT INTO `all clients` VALUES ('WORKERS WORLD MEDIA PRODUCTIONS', 'Amaanullah Ayub', 'CTN_l_014', 'Cape Town ');
INSERT INTO `all clients` VALUES ('WORKERS WORLD MEDIA PRODUCTIONS - Projects', 'Amaanullah Ayub', 'CTN_l_018', 'Cape Town ');
INSERT INTO `all clients` VALUES ('Xyletate (Pty) Ltd', 'Y.M Paruk', 'DBN_l_007', 'Durban');
INSERT INTO `all clients` VALUES ('YHB Enterprise Partnership', 'M. Haffejee', 'DBN_l_023', 'Durban');
INSERT INTO `all clients` VALUES ('ZARX (Pty) Ltd', 'Kallen S.', 'SNH_l_058', 'Johannesburg');
INSERT INTO `all clients` VALUES ('Zwartkop Golf Estate Homeowners Association - Utilities', 'RP Goldes', 'PTR_l_027', 'Pretoria ');
INSERT INTO `all clients` VALUES ('Zelpy 2940 (Pty) Ltd', 'Y.M Paruk', 'DBN_l_008', 'Durban');
INSERT INTO `all clients` VALUES ('Zwartkop Golf Estate Homeowners Association - Levies', 'RP Goldes', 'PTR_l_026', 'Pretoria ');
INSERT INTO `all clients` VALUES ('TESTRRRRR', 'Sangeeta Kallen', 'SDFRRRRRRRRRR', 'Johannesburg');
